package com.example.attendancetest.models

data class Attendance(
    val `1`: String,
    val `10`: String,
    val `11`: String,
    val `12`: String,
    val `13`: String,
    val `14`: String,
    val `15`: String,
    val `16`: String,
    val `17`: String,
    val `18`: String,
    val `19`: String,
    val `2`: String,
    val `20`: String,
    val `21`: String,
    val `22`: String,
    val `23`: String,
    val `24`: String,
    val `25`: String,
    val `26`: String,
    val `27`: String,
    val `28`: String,
    val `29`: String,
    val `3`: String,
    val `30`: String,
    val `4`: String,
    val `5`: String,
    val `6`: String,
    val `7`: String,
    val `8`: String,
    val `9`: String
)